[2022-02-01 12:58:37,176] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_dag.download_data_task scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2022-02-01 12:58:37,187] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_dag.download_data_task scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2022-02-01 12:58:37,188] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 12:58:37,188] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-01 12:58:37,188] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 12:58:37,525] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_data_task> on 2019-03-01 00:00:00+00:00
[2022-02-01 12:58:38,070] {standard_task_runner.py:52} INFO - Started process 7595 to run task
[2022-02-01 12:58:38,075] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_fhv_dag', 'download_data_task', 'scheduled__2019-03-01T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_fhv_dag.py', '--cfg-path', '/tmp/tmpe63jp9_y', '--error-file', '/tmp/tmpks14a1y_']
[2022-02-01 12:58:38,076] {standard_task_runner.py:77} INFO - Job 9: Subtask download_data_task
[2022-02-01 12:58:38,329] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_fhv_dag.download_data_task scheduled__2019-03-01T00:00:00+00:00 [running]> on host 153a4cabbd26
[2022-02-01 12:58:38,531] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-02-01 12:58:38,835] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_fhv_dag
AIRFLOW_CTX_TASK_ID=download_data_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-01T00:00:00+00:00
[2022-02-01 12:58:38,837] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-01 12:58:38,838] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-03.csv > /opt/***/fhv_tripdata_2019-03.csv']
[2022-02-01 12:58:38,846] {subprocess.py:85} INFO - Output:
[2022-02-01 12:59:24,444] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-02-01 12:59:24,446] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 7595. PIDs of all processes in the group: [7597, 7598, 7595]
[2022-02-01 12:59:24,447] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 7595
[2022-02-01 12:59:24,448] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-02-01 12:59:24,448] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2022-02-01 12:59:24,540] {process_utils.py:70} INFO - Process psutil.Process(pid=7597, status='terminated', started='12:58:38') (7597) terminated with exit code None
[2022-02-01 12:59:24,543] {process_utils.py:70} INFO - Process psutil.Process(pid=7595, status='terminated', exitcode=0, started='12:58:37') (7595) terminated with exit code 0
[2022-02-01 12:59:24,543] {process_utils.py:70} INFO - Process psutil.Process(pid=7598, status='terminated', started='12:58:38') (7598) terminated with exit code None
[2022-02-01 13:04:36,501] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_dag.download_data_task scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2022-02-01 13:04:36,517] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_dag.download_data_task scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2022-02-01 13:04:36,518] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 13:04:36,519] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-01 13:04:36,519] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 13:04:36,556] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_data_task> on 2019-03-01 00:00:00+00:00
[2022-02-01 13:04:36,561] {standard_task_runner.py:52} INFO - Started process 8410 to run task
[2022-02-01 13:04:36,564] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_fhv_dag', 'download_data_task', 'scheduled__2019-03-01T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_fhv_dag.py', '--cfg-path', '/tmp/tmp1h5p43j0', '--error-file', '/tmp/tmpvn3r7dbc']
[2022-02-01 13:04:36,565] {standard_task_runner.py:77} INFO - Job 16: Subtask download_data_task
[2022-02-01 13:04:36,656] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_fhv_dag.download_data_task scheduled__2019-03-01T00:00:00+00:00 [running]> on host 153a4cabbd26
[2022-02-01 13:04:36,732] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-02-01 13:04:36,785] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_fhv_dag
AIRFLOW_CTX_TASK_ID=download_data_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-01T00:00:00+00:00
[2022-02-01 13:04:36,787] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-01 13:04:36,788] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-03.csv > /opt/***/fhv_tripdata_2019-03.csv']
[2022-02-01 13:04:36,797] {subprocess.py:85} INFO - Output:
[2022-02-01 13:05:32,118] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-01 13:05:32,759] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_fhv_dag, task_id=download_data_task, execution_date=20190301T000000, start_date=20220201T130436, end_date=20220201T130532
[2022-02-01 13:05:32,831] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-01 13:05:33,013] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
